#!/bin/bash

if [ $USER == 'root' ]; then USER=$SUDO_USER; HOME="/home/${SUDO_USER}"; fi
while [[ "${HOME}" == "/root" || ! -d "${HOME}" ]]; do
  echo "USER HOME PATH ${HOME} IS INVALID!";
  read -p "Enter username: " USER;
  HOME=`echo "/home/${USER}"`;
done
export HOME user;

echo "CHECKING FOR EXISTANCE OF ${HOME}/Projects/.manifest";
if [ ! -d ${HOME}/Projects/ ]; then
  mkdir ${HOME}/Projects;
fi
if [ ! -f ${HOME}/Projects/.manifest ]; then
  echo "...ADDING ${HOME}/Projects/.manifest file"
  touch ${HOME}/Projects/.manifest;
fi
sudo chown -R ${USER}:${USER} ${HOME}/Projects/.manifest;

declare DOMAIN=${HOSTNAME}.lan
virtualhosts-from-manifest;
