#!/bin/bash

if [ $USER == 'root' ]; then USER=$SUDO_USER; HOME="/home/${SUDO_USER}"; fi
while [[ "${HOME}" == "/root" || ! -d "${HOME}" ]]; do
  echo "USER HOME PATH ${HOME} IS INVALID!";
  read -p "Enter username: " USERNAME
  HOME=`echo "/home/${USERNAME}"`;
done
export HOME;

echo "CHECKING FOR EXISTANCE OF ${HOME}/Projects/.manifest";
if [ ! -d ${HOME}/Projects/ ]; then
  mkdir ${HOME}/Projects;
fi
if [ ! -f ${HOME}/Projects/.manifest ]; then
  echo "...ADDING ${HOME}/Projects/.manifest file"
  touch ${HOME}/Projects/.manifest;
  #sudo chmod 755 postinst;
  #sudo chown ${USER}:${USER} postinst;
fi
declare DOMAIN=${HOSTNAME}.lan
#virtualhosts-from-manifest;
