#!/bin/bash -eu

if [[ "$0" != "tools/test" && "$0" != "./tools/test" ]]; then
  echo "Must be run from parent project containing directory NOT $0";
  exit 1;
fi

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2;
  exit 1;
fi

if [ $USER == 'root' ]; then USER=$SUDO_USER; HOME="/home/${SUDO_USER}"; fi
while [[ "${HOME}" == "/root" || ! -d "${HOME}" ]]; do
  echo "USER HOME PATH ${HOME} IS INVALID!";
  read -p "Enter username: " USER
  HOME=`echo "/home/${USER}"`;
done
export HOME USER;

RESPONSE=;
log_response () {
  echo -e "$1\n";
  RESPONSE+="$1\n";
}

sudo tools/package --deploy;

# CLEAN UP
GOOD=0;
trap clean EXIT;
clean () {
  echo -e "\nCLEAN UP";
  rm -f /etc/webshop/skel/application/02-userRequierments/update.flag;
  virtualhost "Test VH 1" remove || true;
  virtualhost "Test VH 2" remove || true;
  virtualhost "Test WP 1" remove || true;
  virtualhost "Test WP 2" remove || true;
  sudo rm -rf "${HOME}/Projects/Test VH 1";
  sudo rm -rf "${HOME}/Projects/Test VH 2";
  sudo rm -rf "${HOME}/Projects/Test WP 1";
  sudo rm -rf "${HOME}/Projects/Test WP 2";
  systemctl restart apache2.service;
  if [[ ${GOOD} == 1 ]]; then
    echo -e "\nFULL REPORT";
    echo -e $RESPONSE;
  else 
    echo -e "\nTESTS \e[0;31mFAILED TO COMPLETE!\e[0m $@";
    exit 1;
  fi
}

# check skel base/www/assets/func|media|style all exist
echo "TESTING skel base/www/assets/func|media|style all exist";
if [ -f /etc/webshop/skel/base/www/assets/func/README.md ]; then
  if [ -f /etc/webshop/skel/base/www/assets/media/README.md ]; then
    if [ -f /etc/webshop/skel/base/www/assets/style/README.md ]; then
      log_response "Test skel base/www/assets/func|media|style all exist \e[0;32mSUCCESSFULL\e[0m";
    else
      log_response "Test skel base/www/assets/style exists \e[0;31mFAILED!\e[0m - unable to confirm style directory exists";
    fi
  else
    log_response "Test skel base/www/assets/media exists \e[0;31mFAILED!\e[0m - unable to confirm media directory exists";
  fi
else
  log_response "Test skel base/www/assets/func exists \e[0;31mFAILED!\e[0m - unable to confirm func directory exists";
fi

# get-full-domain
echo "TESTING get-full-domain";
if [[ `get-full-domain www.example.com` != www.example.com ]]; then
  log_response "get-full-domain Test \e[0;31mFAILED!\e[0m - unable to confirm www.example.com";
else
  if [[ `get-full-domain example.com` != example.com ]]; then
    log_response "get-full-domain Test \e[0;31mFAILED!\e[0m - unable to confirm example.com";
  else
    if [[ `get-full-domain test` != test.${HOSTNAME}.lan ]]; then
      log_response "get-full-domain Test \e[0;31mFAILED!\e[0m - unable to confirm test.${HOSTNAME}.lan";
    else
      log_response "get-full-domain Test \e[0;32mSUCCESSFULL\e[0m"; 
    fi
  fi
fi

# virtualhost-get-domain
echo "TESTING virtualhost-get-domain";
DEFAULT=`virtualhost-get-domain 000-default`
if [[ "${DEFAULT}" != www.${HOSTNAME}.lan ]]; then
  log_response "virtualhost-get-domain Test \e[0;31mFAILED!\e[0m";
else
  log_response "virtualhost-get-domain Test \e[0;32mSUCCESSFULL\e[0m"; 
fi

# virtualhost-edit
echo "TESTING virtualhost-edit";
echo "SETTING UP pre test";
sudo /bin/cp /etc/webshop/skel/vhost/base.txt /etc/apache2/sites-available/testedit.conf;
sudo virtualhost-edit testedit edit.${HOSTNAME}.lan;
if grep "ServerName edit\.${HOSTNAME}\.lan" "/etc/apache2/sites-available/testedit.conf"; then
  if grep "DocumentRoot /var/www/testedit" "/etc/apache2/sites-available/testedit.conf"; then
    if grep "ServerName style.edit\.${HOSTNAME}\.lan" "/etc/apache2/sites-available/testedit.conf"; then
      if grep "DocumentRoot /var/www/style.testedit" "/etc/apache2/sites-available/testedit.conf"; then
        if grep "ServerName func.edit\.${HOSTNAME}\.lan" "/etc/apache2/sites-available/testedit.conf"; then
          if grep "DocumentRoot /var/www/func.testedit" "/etc/apache2/sites-available/testedit.conf"; then
            if grep "ServerName media.edit\.${HOSTNAME}\.lan" "/etc/apache2/sites-available/testedit.conf"; then
              if grep "DocumentRoot /var/www/media.testedit" "/etc/apache2/sites-available/testedit.conf"; then
                if grep "ServerName dev.edit\.${HOSTNAME}\.lan" "/etc/apache2/sites-available/testedit.conf"; then
                  if grep "DocumentRoot /var/www/dev.testedit" "/etc/apache2/sites-available/testedit.conf"; then
                    log_response "virtualhost-edit Test \e[0;32mSUCCESSFULL\e[0m";
                  else
                    log_response "virtualhost-edit Test \e[0;31mFAILED!\e[0m - unable to confirm dev DocumentRoot";
                  fi
                else
                  log_response "virtualhost-edit Test \e[0;31mFAILED!\e[0m - unable to confirm dev ServerName";
                fi
              else
                log_response "virtualhost-edit Test \e[0;31mFAILED!\e[0m - unable to confirm media DocumentRoot";
              fi
            else
              log_response "virtualhost-edit Test \e[0;31mFAILED!\e[0m - unable to confirm media ServerName";
            fi
          else
            log_response "virtualhost-edit Test \e[0;31mFAILED!\e[0m - unable to confirm func DocumentRoot";
          fi
        else
          log_response "virtualhost-edit Test \e[0;31mFAILED!\e[0m - unable to confirm func ServerName";
        fi
      else
        log_response "virtualhost-edit Test \e[0;31mFAILED!\e[0m - unable to confirm style DocumentRoot";
      fi
    else
      log_response "virtualhost-edit Test \e[0;31mFAILED!\e[0m - unable to confirm style ServerName";
    fi
  else
    log_response "virtualhost-edit Test \e[0;31mFAILED!\e[0m - unable to confirm DocumentRoot";
  fi
else
  log_response "virtualhost-edit Test \e[0;31mFAILED!\e[0m - unable to confirm ServerName";
fi
sudo rm /etc/apache2/sites-available/testedit.conf;

# virtualhost TestVH1 add testvh1
echo "TESTING virtualhost add";
echo "SETTING UP pre test";
/bin/mkdir -pv "${HOME}/Projects/Test VH 1";
/bin/cp -dR /etc/webshop/skel/base/* "${HOME}/Projects/Test VH 1";
sudo virtualhost "Test VH 1" add testvh1;
if [[ -d "/var/www/testvh1" ]]; then
  if [[ -d "/var/www/style.testvh1" ]]; then
    if [[ -d "/var/www/func.testvh1" ]]; then
      if [[ -d "/var/www/media.testvh1" ]]; then
        if [[ -d "/var/www/dev.testvh1" ]]; then
          if [[ -f "/etc/apache2/sites-enabled/testvh1.conf" ]]; then
            if grep 'testvh1 "Test VH 1"' "${HOME}/Projects/.manifest"; then
              if curl -sk --head https://testvh1.${HOSTNAME}.lan/ | head -n 1 | grep -E "HTTP/1.[01] 200.|HTTP/1.[01] 403." > /dev/null; then
                log_response "virtualhost 1 add Test \e[0;32mSUCCESSFULL\e[0m";
              else
                log_response "virtualhost 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm site testvh1.${HOSTNAME}.lan is live";
              fi
            else
              log_response "virtualhost 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm entry in .manifest";            
            fi
          else
            log_response "virtualhost 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /etc/apache2/sites-avalible/testvh1.conf";
          fi
        else
          log_response "virtualhost 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/dev.testvh1";
        fi
      else
        log_response "virtualhost 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/media.testvh1";
      fi
    else
      log_response "virtualhost 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/func.testvh1";
    fi
  else
    log_response "virtualhost 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/style.testvh1";
  fi
else
  log_response "virtualhost 1 add Test \e[0;31mFAILED!\e[0m - unable to locate /var/www/testvh1";
fi

# virtualhost TestVH1 remove
echo "TESTING virtualhost remove";
sudo virtualhost "Test VH 1" remove;
if [[ -d "/var/www/testvh1" ]]; then
  log_response "virtualhost 1 remove Test \e[0;31mFAILED!\e[0m - verify to absence of /var/www/testvh1";
else 
  if [[ -d "/var/www/style.testvh1" ]]; then
    log_response "virtualhost 1 remove Test \e[0;31mFAILED!\e[0m - unable to verify absence of /var/www/style.testvh1";
  else
    if [[ -d "/var/www/func.testvh1" ]]; then
      log_response "virtualhost 1 remove Test \e[0;31mFAILED!\e[0m - unable to verify absence of /var/www/func.testvh1";
    else
      if [[ -d "/var/www/media.testvh1" ]]; then
        log_response "virtualhost 1 remove Test \e[0;31mFAILED!\e[0m - unable to verify absence of /var/www/media.testvh1";
      else
        if [[ -d "/var/www/dev.testvh1" ]]; then
          log_response "virtualhost 1 remove Test \e[0;31mFAILED!\e[0m - unable to verify absence of /var/www/dev.testvh1";
        else
          if [[ -f "/etc/apache2/sites-available/testvh1.conf" ]]; then
              log_response "virtualhost 1 remove Test \e[0;31mFAILED!\e[0m - unable to verify absence of /etc/apache2/sites-avalible/testvh1.conf";
          else
            if grep 'testvh1 "Test VH 1"' "${HOME}/Projects/.manifest"; then
              log_response "virtualhost 1 remove Test \e[0;31mFAILED!\e[0m - unable to confirm absence of entry in .manifest";
            else
              log_response "virtualhost 1 remove Test \e[0;32mSUCCESSFULL\e[0m";
            fi
          fi
        fi
      fi
    fi
  fi
fi

# virtualhosts-from-manifest
echo "TESTING virtualhosts-from-manifest";
echo "SETTING UP pre test";
echo "testvh1 \"Test VH 1\"" >> ${HOME}/Projects/.manifest;
/bin/mkdir -pv "${HOME}/Projects/Test VH 2";
/bin/cp -dR /etc/webshop/skel/base/* "${HOME}/Projects/Test VH 2";
echo "testvh2 \"Test VH 2\"" >> ${HOME}/Projects/.manifest;
virtualhosts-from-manifest
if [[ -d "/var/www/testvh1" ]]; then
  if [[ -d "/var/www/style.testvh1" ]]; then
    if [[ -d "/var/www/func.testvh1" ]]; then
      if [[ -d "/var/www/media.testvh1" ]]; then
        if [[ -d "/var/www/dev.testvh1" ]]; then
          if [[ -f "/etc/apache2/sites-available/testvh1.conf" ]]; then
            if grep 'testvh1 "Test VH 1"' "${HOME}/Projects/.manifest"; then
              if [[ -d "/var/www/testvh2" ]]; then
                if [[ -d "/var/www/style.testvh2" ]]; then
                  if [[ -d "/var/www/func.testvh2" ]]; then
                    if [[ -d "/var/www/media.testvh2" ]]; then
                      if [[ -d "/var/www/dev.testvh2" ]]; then
                        if [[ -f "/etc/apache2/sites-available/testvh2.conf" ]]; then
                          if grep "testvh2 \"Test VH 2\"" "${HOME}/Projects/.manifest"; then
                            log_response "virtualhosts-from-manifest Test \e[0;32mSUCCESSFULL\e[0m";
                          else
                            log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to confirm entry in .manifest testvh2";            
                          fi
                        else
                          log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /etc/apache2/sites-avalible/testvh2.conf";
                        fi
                      else
                        log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/dev.testvh2";
                      fi
                    else
                      log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/media.testvh2";
                    fi
                  else
                    log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/func.testvh2";
                  fi
                else
                  log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/style.testvh2";
                fi
              else
                log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/testvh2";
              fi
            else
              log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to confirm entry in .manifest testvh1";            
            fi
          else
            log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /etc/apache2/sites-avalible/testvh1.conf";
          fi
        else
          log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/dev.testvh1";
        fi
      else
        log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/media.testvh1";
      fi
    else
      log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/func.testvh1";
    fi
  else
    log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/style.testvh1";
  fi
else
  log_response "virtualhosts-from-manifest Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/testvh1";
fi

# virtualhost-edit (change domain) testvh1
echo "TESTING virtualhost-edit Rename (change domain)";
sudo virtualhost-edit testvh1 new-domain.lan;
if grep "ServerName new-domain.lan" "/etc/apache2/sites-available/testvh1.conf"; then
  if grep "DocumentRoot /var/www/testvh1" "/etc/apache2/sites-available/testvh1.conf"; then
    log_response "virtualhost-edit Rename Test \e[0;32mSUCCESSFULL\e[0m";
  else
    log_response "virtualhost-edit Rename Test \e[0;31mFAILED!\e[0m - unable to confirm DocumentRoot";
  fi
else
  log_response "virtualhost-edit Rename Test \e[0;31mFAILED!\e[0m - unable to confirm ServerName";
fi

# virtualhost-append-copy
echo "TESTING virtualhost-append-copy";
sudo virtualhost-append-copy testvh1;
if grep "ServerName copy.new-domain.lan" "/etc/apache2/sites-available/testvh1.conf"; then
  if grep "DocumentRoot /var/www/copy.testvh1" "/etc/apache2/sites-available/testvh1.conf"; then
    log_response "virtualhost-append-copy Test \e[0;32mSUCCESSFULL\e[0m";
  else
    log_response "virtualhost-append-copy Test \e[0;31mFAILED!\e[0m - unable to confirm DocumentRoot";
  fi
else
  log_response "virtualhost-append-copy Test \e[0;31mFAILED!\e[0m - unable to confirm ServerName";
fi

# copy-current-website
echo "TESTING copy-current-website";
copy-current-website "Test VH 2" www.example.com;
sudo systemctl restart apache2;
if [[ -d "${HOME}/Projects/Test VH 2/copy" ]]; then
  if [[ -d "/var/www/copy.testvh2" ]]; then
    if grep "ServerName copy.testvh2\.${HOSTNAME}\.lan" "/etc/apache2/sites-available/testvh2.conf"; then
      if [[ ! -z $(curl -sk --head "https://copy.testvh2.${HOSTNAME}.lan/" | head -n 1 | grep -E "HTTP/1.[01] 200.|HTTP/1.[01] 403.") ]]; then
        log_response "copy-current-website Test \e[0;32mSUCCESSFULL\e[0m";
      else
        log_response "copy-current-website Test \e[0;31mFAILED!\e[0m - unable to confirm site copy.testvh2.${HOSTNAME}.lan is live";
      fi
    else
      log_response "copy-current-website Test \e[0;31mFAILED!\e[0m - unable to confirm ServerName in virtual host file";
    fi
  else 
    log_response "copy-current-website Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/copy.testvh2";
  fi
else
    log_response "copy-current-website Test \e[0;31mFAILED!\e[0m - unable to localte ${HOME}/Projects/TestVH2/copy";
fi

# webproject testwp1 new (basic)
echo "TESTING webproject new (basic)";
webproject "Test WP 1" new
if [[ -d "${HOME}/Projects/Test WP 1" ]]; then
  if [[ -d "/var/www/testwp1" ]]; then
    if [[ -d "/var/www/style.testwp1" ]]; then
      if grep "testwp1.${HOSTNAME}.lan" "${HOME}/Projects/Test WP 1/www/assets/style/docs/base.html"; then
        TAG_SITE_ID=`echo "testwp1.${HOSTNAME}.lan" | sed 's/\./-/g'`;
        if grep "${TAG_SITE_ID}" "${HOME}/Projects/Test WP 1/www/assets/style/docs/base.html"; then
          if [[ -d "/var/www/func.testwp1" ]]; then
            if grep "testwp1.${HOSTNAME}.lan" "${HOME}/Projects/Test WP 1/www/assets/func/index.html"; then
              if grep "${TAG_SITE_ID}" "${HOME}/Projects/Test WP 1/www/assets/func/index.html"; then
                if grep "testwp1.${HOSTNAME}.lan" "${HOME}/Projects/Test WP 1/www/assets/func/docs/drag.scratch"; then
                  if grep "${TAG_SITE_ID}" "${HOME}/Projects/Test WP 1/www/assets/func/docs/drag.scratch"; then
                    if [[ -d "/var/www/media.testwp1" ]]; then
                      if grep "testwp1.${HOSTNAME}.lan" "${HOME}/Projects/Test WP 1/www/assets/media/index.html"; then
                        if grep "${TAG_SITE_ID}" "${HOME}/Projects/Test WP 1/www/assets/media/index.html"; then
                          if [[ -d "/var/www/dev.testwp1" ]]; then
                            if [[ -f "/etc/apache2/sites-enabled/testwp1.conf" ]]; then
                              if [[ -d "${HOME}/Projects/Test WP 1/www" ]]; then
                                if grep 'testwp1 "Test WP 1"' "${HOME}/Projects/.manifest"; then
                                  if curl -sk --head https://testwp1.${HOSTNAME}.lan/ | head -n 1 | grep -E "HTTP/1.[01] 200.|HTTP/1.[01] 403." > /dev/null; then
                                    log_response "webproject 1 add Test \e[0;32mSUCCESSFULL\e[0m";
                                  else
                                    log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm site testwp1.${HOSTNAME}.lan is live";
                                  fi
                                else
                                  log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm entry in .manifest";            
                                fi
                              else
                                log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to localte '${HOME}/Projects/Test WP 1/www'";
                              fi
                            else
                              log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /etc/apache2/sites-avalible/testwp1.conf";
                            fi
                          else
                            log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/dev.testwp1";
                          fi
                        else
                          log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm site id replacement in ...media/index.html";
                        fi
                      else
                        log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm style domain replacement in ...media/index.html";
                      fi
                    else
                      log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/media.testwp1";
                    fi
                  else
                    log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm site id replacement in ...func/docs/drag.scratch";
                  fi
                else
                  log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm style domain replacement in ...func/docs/drag.scratch";
                fi
              else
                log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm site id replacement in ...func/index.html";
              fi
            else
              log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm style domain replacement in ...func/index.html";
            fi
          else
            log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/func.testwp1";
          fi
        else
          log_response "virtualhost 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm media domain replacement in ...style/docs/base.html";
        fi
      else
        log_response "virtualhost 1 add Test \e[0;31mFAILED!\e[0m - unable to confirm site id replacement in ...style/docs/base.html";
      fi
    else
      log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/style.testwp1";
    fi
  else
    log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/testwp1";
  fi
else
  log_response "webproject 1 add Test \e[0;31mFAILED!\e[0m - unable to localte ${HOME}/Projects/Test\ WP\ 1";
fi

# webproject testwp2(t2) new (with all extras)
echo "TESTING webproject new (with all extras)";
webproject "Test WP 2" new --domain t2 --application --copy www.example.com
if [[ -d "${HOME}/Projects/Test WP 2" ]]; then
  if [[ -d "/var/www/testwp2" ]]; then
    if [[ -d "/var/www/style.testwp2" ]]; then
      if [[ -d "/var/www/func.testwp2" ]]; then
        if [[ -d "/var/www/media.testwp2" ]]; then
          if [[ -d "/var/www/dev.testwp2" ]]; then
            if [[ -d "/var/www/copy.testwp2" ]]; then
              if [[ -f "/etc/apache2/sites-enabled/testwp2.conf" ]]; then
                if [[ -d "${HOME}/Projects/Test WP 2/www" ]]; then
                  if [[ -d "${HOME}/Projects/Test WP 2/copy" ]]; then
                    if [[ -f "${HOME}/Projects/Test WP 2/www/controller.php" ]]; then
                      if grep 'testwp2 "Test WP 2"' "${HOME}/Projects/.manifest"; then
                        if curl -sk --head https://t2.${HOSTNAME}.lan/ | head -n 1 | grep -E "HTTP/1.[01] 200.|HTTP/1.[01] 403." > /dev/null; then
                          log_response "webproject 2 add Test \e[0;32mSUCCESSFULL\e[0m";
                        else
                          log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to confirm site t2.${HOSTNAME}.lan is live";
                        fi
                      else
                        log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to confirm entry in .manifest";            
                      fi
                    else
                      log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte '${HOME}/Projects/Test WP 2/www/controller.php'";
                    fi
                  else
                    log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte '${HOME}/Projects/Test WP 2/copy'";
                  fi
                else
                  log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte '${HOME}/Projects/Test WP 2/www'";
                fi
              else
                log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte /etc/apache2/sites-avalible/testwp2.conf";
              fi
            else
              log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/copy.testwp2";
            fi
          else
            log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/dev.testwp2";
          fi
        else
          log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/media.testwp2";
        fi
      else
        log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/func.testwp2";
      fi
    else
      log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/style.testwp2";
    fi
  else
    log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/testwp2";
  fi
else
  log_response "webproject 2 add Test \e[0;31mFAILED!\e[0m - unable to localte ${HOME}/Projects/Test\ WP\ 2";
fi

# webproject "PROJECT_NAME" extend --domain DOMAIN --application --copy COPY_DOMAIN
echo "TESTING webproject extend (with all extras)";
webproject "Test WP 1" extend --domain t1 --application --copy www.example.com
if [[ -d "${HOME}/Projects/Test WP 1/copy" ]]; then
  if [[ -f "${HOME}/Projects/Test WP 1/www/controller.php" ]]; then
    if grep 'testwp1 "Test WP 1"' "${HOME}/Projects/.manifest"; then
      if [[ ! -z $(curl -sk --head https://t1.${HOSTNAME}.lan/ | head -n 1 | grep -E "HTTP/1.[01] 200.|HTTP/1.[01] 403.") ]]; then
        if [[ ! -z $(curl -sk --head https://copy.testwp1.${HOSTNAME}.lan/ | head -n 1 | grep -E "HTTP/1.[01] 200.|HTTP/1.[01] 403.") ]]; then
          log_response "webproject 1 extend Test \e[0;32mSUCCESSFULL\e[0m";
        else
          log_response "webproject 1 extend Test \e[0;31mFAILED!\e[0m - unable to confirm site copy.testwp1.${HOSTNAME}.lan is live";
        fi
      else
          log_response "webproject 1 extend Test \e[0;31mFAILED!\e[0m - unable to confirm site t1.${HOSTNAME}.lan is live";
      fi
    else
      log_response "webproject 1 extend Test \e[0;31mFAILED!\e[0m - unable to confirm entry in .manifest";            
    fi
  else
    log_response "webproject 1 extend Test \e[0;31mFAILED!\e[0m - unable to localte '${HOME}/Projects/Test WP 1/www/controller.php'";
  fi
else
  log_response "webproject 1 extend Test \e[0;31mFAILED!\e[0m - unable to localte '${HOME}/Projects/Test WP 1/copy'";
fi

# webproject "PROJECT_NAME" update --domain new-domain.lan
echo "TESTING webproject update (change domain, update app skeleton & website copy)";
echo "SETTING UP pre test";
sudo echo "FLAG" >> /var/www/testwp2/index.html;
sudo touch ${HOME}/Projects/Test\ WP\ 2/02-userRequierments/manual.flag;
sudo touch /etc/webshop/skel/application/02-userRequierments/update.flag;
sudo touch ${HOME}/Projects/Test\ WP\ 2/copy/temp.flag;
webproject "Test WP 2" update --domain testwp2 --application --copy www.example.com
if grep "ServerName testwp2\.${HOSTNAME}\.lan" "/etc/apache2/sites-available/testwp2.conf"; then
  if grep "DocumentRoot /var/www/testwp2" "/etc/apache2/sites-available/testwp2.conf"; then
    if [ -f "${HOME}/Projects/Test WP 2/www/controller.php" ]; then
      if [ `grep "FLAG" "/var/www/testwp2/index.html"` == "FLAG" ]; then
        if [[ -f "/var/www/copy.testwp2/index.html" ]]; then
          if [[ -f "${HOME}/Projects/Test WP 2/02-userRequierments/manual.flag" && -f "${HOME}/Projects/Test WP 2/02-userRequierments/update.flag" ]]; then
            log_response "webproject 2 update Test \e[0;32mSUCCESSFULL\e[0m";
          else
            log_response "webproject 2 update Test \e[0;31mFAILED!\e[0m - unable to confirm updated application skeleton";
          fi
        else
          log_response "webproject 2 update Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/copy.testwp2/index.html";
        fi
      else
        log_response "webproject 2 update Test \e[0;31mFAILED!\e[0m - unable to confirm modified '${HOME}/Projects/Test WP 2/www/index.html' NOT overwriten";
      fi
    else
      log_response "webproject 2 update Test \e[0;31mFAILED!\e[0m - unable to localte '${HOME}/Projects/Test WP 2/www/controller.php'";
    fi
  else
    log_response "webproject 2 update Test \e[0;31mFAILED!\e[0m - unable to confirm DocumentRoot";
  fi
else
  log_response "webproject 2 update Test \e[0;31mFAILED!\e[0m - unable to confirm ServerName";
fi

# webproject reset (change domain, reset app)
echo "TESTING webproject reset (change domain, reset app skeleton & website copy)";
echo "SETTING UP pre test";
sudo cp ${HOME}/Projects/Test\ WP\ 2/ramp.ini.example ${HOME}/Projects/Test\ WP\ 2/ramp.ini;
webproject "Test WP 2" reset --domain t2 --application --copy www.example.com
if grep "ServerName t2\.${HOSTNAME}\.lan" "/etc/apache2/sites-available/testwp2.conf"; then
  if grep "DocumentRoot /var/www/testwp2" "/etc/apache2/sites-available/testwp2.conf"; then
    if [ -f "${HOME}/Projects/Test WP 2/www/controller.php" ]; then
      if [[ -f "/var/www/copy.testwp2/index.html" ]]; then
        if [[ ! -f "${HOME}/Projects/Test WP 2/ramp.ini" ]]; then
          if [[ ! -z $(curl -sk --head https://t2.${HOSTNAME}.lan/ | head -n 1 | grep -E "HTTP/1.[01] 200.|HTTP/1.[01] 403.") ]]; then
            if [[ ! -z $(curl -sk --head https://copy.t2.${HOSTNAME}.lan/ | head -n 1 | grep -E "HTTP/1.[01] 200.|HTTP/1.[01] 403.") ]]; then
              log_response "webproject 2 reset Test \e[0;32mSUCCESSFULL\e[0m";
            else
              log_response "webproject 2 reset Test \e[0;31mFAILED!\e[0m - unable to confirm site copy.t2.${HOSTNAME}.lan is live";
            fi
          else
            log_response "webproject 1 extend Test \e[0;31mFAILED!\e[0m - unable to confirm site t1.${HOSTNAME}.lan is live";
          fi
        else
          log_response "webproject 2 reset Test \e[0;31mFAILED!\e[0m - unable to confirm ramp.ini removed";
        fi
      else
        log_response "webproject 2 reset Test \e[0;31mFAILED!\e[0m - unable to localte /var/www/copy.t2/index.html";
      fi
    else
      log_response "webproject 2 reset Test \e[0;31mFAILED!\e[0m - unable to localte '${HOME}/Projects/Test WP 2/www/controller.php'";
    fi
  else
    log_response "webproject 2 reset Test \e[0;31mFAILED!\e[0m - unable to confirm DocumentRoot";
  fi
else
  log_response "webproject 2 reset Test \e[0;31mFAILED!\e[0m - unable to confirm ServerName";
fi

GOOD=1;
exit 0;
